name: CI/CD Practice

on:
  push:
    branches:
      - ci-cd-practice

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          
      - name: Install Dependencies
        run: npm install

      - name: Build the application
        run: npm run build


      -  name: List the build file
         run: ls -la dist



      -  name: Clean Old files on ec2 
         uses: appleboy/ssh-action@v1
         with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: | 
            rm -rf ~/react-app/*



      - name: Copy build to EC2 
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/*"
          target: "~/react-app"

     

      -  name: Serve React app on EC2 using PM2
         uses: appleboy/ssh-action@v1
         with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
           pm2 stop react-app || true
           pm2 serve ~/react-app/dist 3000 --name react-app --spa
           pm2 save
